name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.100-preview.3.23178.7

      - name: Restore dependencies
        run: dotnet restore GH-Pages-Blazor-WebAssembly/GH-Pages-Blazor-WebAssembly.sln

      - name: Build and publish
        run: dotnet publish GH-Pages-Blazor-WebAssembly/GH-Pages-Blazor-WebAssembly.sln --configuration Release

      - name: List files in ./GH-Pages-Blazor-WebAssembly/GH-Pages-Blazor-WebAssembly/bin/Release/net8.0/publish/wwwroot/
        run: ls -la ./GH-Pages-Blazor-WebAssembly/GH-Pages-Blazor-WebAssembly/bin/Release/net8.0/publish/wwwroot/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./GH-Pages-Blazor-WebAssembly/GH-Pages-Blazor-WebAssembly/bin/Release/net8.0/publish/wwwroot/
